version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/zcong1993/gin-ratelimit

    steps:
      - checkout
      - run:
          name: get deps
          command: make install
      - run:
          name: test
          command: make test.cov
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
